import * as fs from 'fs';
// eslint-disable-next-line node/no-missing-import
import { execute, projDir, readme } from './util';

const { program } = require('commander');
const replaceSection = require('markdown-replace-section');

const DEBUG = false;

// add autogenerated files that are not in .gitignore to exclude
const EXCLUDE_LIST = ['package-lock.json', 'yarn.lock, pnpm-lock.yaml']
  .join() // join with | as separator not working
  .replace(/, /g, '|');
const sectionName = 'Lines of Code (auto-generated stats)';
const sectionHelp = `
### Line of code generation

The above line of code table is auto generated and should not be edited manually.
Note: \`loc\` should be installed on your system, in order to generate the above stats.
      It will ignore all directories, files that you have in .gitignore.
- \`brew install loc\` # install on mac
`;
/**
 * Note, the "Lines of Code" section cannot be at the end
 * https://github.com/renke/markdown-replace-section/issues/1
 */
async function main() {
  console.log(projDir);
  console.log(`Excluding: ${EXCLUDE_LIST}`);
  const cmd = `cd ${projDir} && git ls-files | grep -vE '${EXCLUDE_LIST}' | xargs loc`;
  console.log(`Running: ${cmd}`);
  const loc = await execute(cmd, !DEBUG);
  let readMeContent: string;

  try {
    readMeContent = fs.readFileSync(readme, 'utf-8');
  } catch (err) {
    console.error(`Error reading file from disk: ${err}`);
    throw err;
  }

  if (!readMeContent.includes(sectionName)) {
    readMeContent = `${readMeContent}\n\n## ${sectionName}\n\n${sectionHelp}`;
  }

  const replaceAllMatches = false;
  readMeContent = replaceSection(
    readMeContent,
    sectionName,
    '```txt<br>' + loc + '```',
    replaceAllMatches
  );

  fs.writeFileSync(readme, readMeContent, { encoding: 'utf8', flag: 'w' });
  console.log(loc, '\n\nREADME.md updated');
}

program.version('0.0.1', '-v, --version').parse(process.argv);

main().catch((err) => {
  console.error(`Error updating Readme.md`, err);
  throw err;
});
