name: Build Workflow
on:
  push:
    branches:
      - feat/*
      - fix/*
      - hotfix/*
      - release/*
      - dev
      - ci
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'apps/**'
      - 'libs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        step: [lint, build, test]
      fail-fast: false
    steps:
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js and cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i

      - name: Run step
        run: |
          if [ "${{ matrix.step }}" == "lint" ]; then
            pnpm run lint
          elif [ "${{ matrix.step }}" == "build" ]; then
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              pnpm run build:main
            elif [ "${{ github.ref }}" == "refs/heads/ci" ]; then
              pnpm run build:ci
            else
              pnpm run build:dev
            fi
          else
            pnpm run test
          fi
