# Name of the workflow
name: Build Workflow

# Trigger the workflow on push events to specific branches and paths
on:
  push:
    branches:
      - feat/* # Feature branches
      - fix/* # Fix branches
      - hotfix/* # Hotfix branches
      - release/* # Release branches
      - dev # Development branch
      - ci # Continuous Integration branch
      - main # Main branch
    paths:
      - '.github/workflows/build.yml' # Workflow file itself
      - 'apps/**' # Apps directory
      - 'libs/**' # Libraries directory

# Job named "build"
jobs:
  build:
    # Run the job on an Ubuntu environment
    runs-on: ubuntu-latest

    # Strategy for the job
    strategy:
      matrix:
        step: [lint, build, test] # Matrix of steps to run
      fail-fast: false # Don't fail the job if one step fails

    # Steps in the job
    steps:
      - name: UTC time in ISO 8601 format
        run: |
          UTC_DATE=$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)
          echo "date=$UTC_DATE" >> "$GITHUB_OUTPUT"

      # Get the version from the package.json file
      # This step retrieves the version from the package.json file using jq.
      - name: Get web app package.json version
        id: web-app
        run: |
          LF_VERSION=$(cat apps/web/package.json | jq -r '.version')
          echo "version=$LF_VERSION" >> "$GITHUB_OUTPUT"

      # Update the app config with the version
      - name: update app config, version, hash, and date
        run: |
          sed -i 's/i-am-a-version/${{steps.web-app.outputs.version}}/g' apps/web/src/cfg/config.json
          sed -i 's/i-am-a-hash/${{github.sha}}/g' apps/web/src/cfg/config.json
          sed -i 's/i-am-a-date/${{steps.web-app.outputs.date}}/g' apps/web/src/cfg/config.json
          echo `cat apps/web/src/cfg/config.json`
        # This step updates the app config with the version.

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        # This step checks out the code with all history.

      # Set up Node.js and cache pnpm
      - name: Set up Node.js and cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use Node.js 18
          cache: 'pnpm' # Cache pnpm dependencies
        # This step sets up Node.js and caches pnpm dependencies.

      # Install dependencies
      - name: Install dependencies
        run: pnpm i
        # This step installs the dependencies using pnpm.

      # Run the step (lint, build, or test)
      - name: Run step
        run: |
          if [ "${{ matrix.step }}" == "lint" ]; then
            pnpm run lint
          elif [ "${{ matrix.step }}" == "build" ]; then
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              pnpm run build:main
            elif [ "${{ github.ref }}" == "refs/heads/ci" ]; then
              pnpm run build:ci
            else
              pnpm run build:dev
            fi
          else
            pnpm run test
          fi
        # This step runs the selected step (lint, build, or test).
